trigger:
  branches:
    include:
      - main
pool:
  vmImage: 'ubuntu-latest'
steps:
  - task: UseNode@1
    inputs:
      versionSpec: '16.x'
      displayName: 'Install Node.js'
  - script: |
      npm install
    displayName: 'Install dependencies'
  - script: |
      npm run build
    displayName: 'Build Next.js project'
  - task: CopyFiles@2
    inputs:
      SourceFolder: '.next'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/site'
    condition: succeeded()
    displayName: 'Prepare files for deployment'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/site'
      ArtifactName: 'site'
    displayName: 'Publish artifact'